# Generated by Django 3.0 on 2021-05-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='Isbn',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='Isbn',
        ),
    ]
