# Generated by Django 3.0 on 2021-05-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Isbn',
            new_name='price',
        ),
    ]
